package(default_visibility = [
    "//ios:__subpackages__",
])

licenses(["notice"])

exports_files([
    "Launch.storyboard",
])

filegroup(
    name = "PhoneAppIcon.xcassets",
    srcs = glob(["PhoneAppIcon.xcassets/**/*"]),
)
